### ISSUE TITLE
Language mismatch in links between apps, apps_in_progress, apps_wishlist

### ISSUE THREAD

**Issue by chtixof** [YunoHost/doc#216]
From https://yunohost.org/#/apps (French) and https://yunohost.org/#/apps_fr (French)
link "Apps en cours" leads to "https://yunohost.org/#/apps_in_progress_en" (English)

From  "https://yunohost.org/#/apps_in_progress_en" (English), 
link "Official apps" leads to "https://yunohost.org/#/apps" (French)

and so on : check also "Apps wishlist".

I don't know your final goal, otherwise, I would have proposed a correction.

Cheers.

**Comment by M5oul** [comment]
Hi chtixof,

What is the problem? I can't see any problem in your talking.
apps_in_progress and apps_wishlist are unique and in english to render things more easy to use.
This pages does not exit in french because we can not maintained two version of theses lists.
For me, redirections between this tree pages are right for a french web browser.

Tell me more about what you think ;)

**Comment by chtixof** [comment]
Bonjour M5oul. I tested again from FF and GC.
- load https://yunohost.org/#/apps_fr => French
- click on "Apps en cours"
- renders page https://yunohost.org/#/apps_in_progress_en => English

**Comment by M5oul** [comment]
Now I can seize the problem. Do a pull request.

**Comment by M5oul** [comment]
Done with https://github.com/YunoHost/doc/pull/217#issuecomment-92071008
Tell me if it is ok for you.
